easy_admin:
  site_name: 'Copyvore Admin'
  formats:
    date: 'd/m/Y'
    time: 'H:i'
    datetime: 'd/m/Y H:i:s'
  design:
    brand_color: '#FD0100'
    assets:
      favicon: 'images/favicon.ico'

  list:
    actions:
      - { name: 'search', icon: 'search', label: 'Rechercher', title: 'Rechercher' }
      - { name: 'new', icon: 'plus', label: 'Ajouter', title: 'Créer' }
      - { name: 'edit', icon: 'pencil', label: 'Editer', title: 'Editer' }
      - { name: 'delete', icon: 'times', label: 'Supprimer', title: 'Supprimer' }

  entities:
    User:
      class: App\Entity\User
      label: 'Utilisateurs'
      list:
        title: 'Liste des %%entity_label%%'
        max_results: 30
        actions:
          - { name: 'show', icon: 'user', label: 'Voir', title: 'Voir' }
        fields:
          - { property: 'name', label: 'Nom' }
          - { property: 'surname', label: 'Prénom' }
          - { property: 'email', label: 'E-mail', type: 'email' }
          - { property: 'phone', label: 'Téléphone' }
      form:
        fields:
          - { type: 'section', label: 'Informations Utilisateur', icon: 'user', css_class: 'danger' }
          - { property: 'name', label: 'Nom', icon: 'user' }
          - { property: 'surname', label: 'Prénom', icon: 'user' }
          - { property: 'email', label: 'E-mail', type: 'email' }
          - { property: 'password', label: 'Mot de passe', type: 'password' }
          - { type: 'section', label: 'Informations additionnelles', icon: 'home', css_class: 'danger' }
          - { property: 'phone', label: 'Téléphone' }
          - { property: 'streetNumber', label: 'Numéro de rue' }
          - { property: 'street', label: 'Rue' }
          - { property: 'city', label: 'Ville' }
          - { property: 'postcode', label: 'Code postal' }
      new:
        title: 'Ajouter un utilisateur'
      edit:
        title: 'Utilisateur (#%%entity_id%%)'
      show:
        title: 'Utilisateur (#%%entity_id%%)'

    Order:
      class: App\Entity\Order
      label: 'Commandes'
      list:
        title: 'Liste des %%entity_label%%'
        max_results: 30
        sort: 'createdAt'
        fields:
          - { property: 'user', label: 'Utilisateur' }
          - { property: 'admin', label: 'Admin' }
          - { property: 'copyType', label: 'Type de copie' }
          - { property: 'createdAt', label: 'Date de commande' }
          - { property: 'number', label: 'Nombre de copies' }
          - { property: 'label', label: 'Libellé' }
      search:
        sort: 'createdAt'
        max_results: 30
      form:
        fields:
          - { type: 'group', css_class: 'col-sm-6', label: 'Informations humaines' }
          - { property: 'user', label: 'Utilisateur', icon: 'user' }
          - { property: 'admin', label: 'Admin', icon: 'user' }
          - { type: 'group', css_class: 'col-sm-6', label: 'Informations commande' }
          - { property: 'copyType', label: 'Type de copie' }
          - { property: 'number', label: 'Nombre de copies' }
          - { property: 'label', label: 'Libellé' }
#          - { property: 'createdAt', label: 'Date de création' }
      new:
        title: 'Créer une commande'
      edit:
        title: 'Commande (#%%entity_id%%)'

    Reload:
      class: App\Entity\Reload
      label: 'Recharges'
      list:
        title: 'Liste des %%entity_label%%'
        max_results: 30
        sort: 'createdAt'
        fields:
          - { property: 'user', label: 'Utilisateur' }
          - { property: 'admin', label: 'Admin' }
          - { property: 'reloadType', label: 'Type de recharge' }
          - { property: 'createdAt', label: 'Date de création' }
      search:
        sort: 'createdAt'
        max_results: 30
      form:
        fields:
          - { property: 'user', label: 'Utilisateur', icon: 'user' }
          - { property: 'admin', label: 'Admin', icon: 'user' }
          - { property: 'reloadType', label: 'Type de recharge' }
#          - { property: 'createdAt', label: 'Date de création' }
      new:
        title: 'Créer une recharge'
      edit:
        title: 'Recharge (#%%entity_id%%)'

    ReloadType:
      class: App\Entity\ReloadType
      label: 'Types de recharge'
      list:
        title: 'Liste des %%entity_label%%'
        max_results: 30
        fields:
          - { property: 'number', label: 'Nombre' }
          - { property: 'unitPrice', label: 'Prix unitaire', type: 'money', type_options: { currency: 'EUR' } }
          - { property: 'amount', label: 'Montant', type: 'money', type_options: { currency: 'EUR' } }
          - { property: 'copyType', label: 'Copie' }
          - { property: 'isAvailable', label: 'Active' }
      form:
        fields:
          - { property: 'number', label: 'Nombre de copies' }
          - { property: 'unitPrice', label: 'Prix unitaire', type: 'money', type_options: { currency: 'EUR' } }
          - { property: 'copyType', label: 'Type de copie' }
          - { property: 'isAvailable', label: 'Active' }
      new:
        title: 'Créer un type de recharge'
      edit:
        title: 'Type de recharge (#%%entity_id%%)'

    CopyType:
      class: App\Entity\CopyType
      label: 'Types de copie'
      list:
        title: 'Liste des %%entity_label%%'
        max_results: 30
        fields:
          - { property: 'type', label: 'Type' }
      new:
        title: 'Créer un type de copie'
      edit:
        title: 'Type de copie (#%%entity_id%%)'

    Admin:
      class: App\Entity\Admin
      label: 'Admins'
      list:
        title: 'Liste des %%entity_label%%'
        max_results: 30
        fields:
          - { property: 'login', label: 'Login' }
      form:
        fields:
          - { property: 'login', label: 'Login', icon: 'user' }
          - { property: 'password', label: 'Mot de passe', type: 'password' }
      new:
        title: 'Ajouter un admin'
      edit:
        title: 'Admin (#%%entity_id%%)'
