easy_admin:
  site_name: 'Copyvore Admin'
  design:
    brand_color: '#FD0100'
  entities:
    - App\Entity\User
    - App\Entity\Order
    - App\Entity\Reload
    - App\Entity\ReloadType
    - App\Entity\CopyType
    - App\Entity\Admin
