framework:
    secret: '%env(APP_SECRET)%'
    default_locale: fr
    validation: { enabled: true }
    csrf_protection: { enabled: true }

    #http_method_override: true

    # uncomment this entire section to enable sessions
    session:
        handler_id: ~

    #esi: ~
    #fragments: ~
    php_errors:
        log: true
